# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Studying Seoul
tagline:             'A very American look at a very Korean place'
description:         >
                      안녕하세요! My name is Colin -- I'm a sophomore at the University
                      of Maryland. I'm studying at Yonsei University this semester,
                      which is a long way from home. I've already almost exhausted
                      my knowledge of Korean in this introduction, but hope to remedy this
                      while exploring Seoul.
url:                 http://studyingseoul.com
baseurl:             ''
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Colin Burr
  url:               https://twitter.com/ColinABurr
  email:             colin.a.burr@gmail.com

# Github
github:
  repo:              https://github.com/sw3dish/studying_seoul_jekyll

# Custom vars
version:             1.0.0

gems:               [jekyll-gist, jekyll-paginate]
